src/lang/en.json
src/system.json
src/system/config.ts
src/system/data/actor/common.ts
src/system/data/item/index.ts
src/system/data/item/injury.ts
src/system/types/config.ts
src/system/types/cosmere.ts

Partially addresses #5 
Adding injury support to the character data model. While injuries themselves (among other conditions) should be Items or some other kind of EmbeddedDocument that lives in a character, we also want easy access to the number of injuries one has among their other conditions. We'll want a derived field for quick access to the number of injuries for Injury Rolls, as well as particular support for Injury Items.
Done:
- Create derived `injuries` field in the common actor data model
- Implement `Injury` item type
- create additional fields to model an injury (such as `duration`)
- Update Actor to derive `injuries` data from owned Injury items

feat(data): add injuries support to character data model

---

rollup.config.js
src/declarations/foundry/client/data/abstract/client-document.d.ts
src/declarations/foundry/client/data/documents/actor.d.ts
src/declarations/foundry/common/abstract/data.d.ts
src/index.ts
src/lang/en.json
src/style.scss
src/style/sheets/actor/character.scss
src/style/sheets/sheet.scss
src/system/applications/actor/base-sheet.ts
src/system/config.ts
src/system/data/item/action.ts
src/system/data/item/armor.ts
src/system/data/item/mixins/activatable.ts
src/system/data/item/mixins/attacking.ts
src/system/data/item/mixins/damaging.ts
src/system/data/item/mixins/description.ts
src/system/data/item/mixins/equippable.ts
src/system/data/item/mixins/physical.ts
src/system/data/item/mixins/traits.ts
src/system/data/item/weapon.ts
src/system/documents/actor.ts
src/system/documents/item.ts
src/system/types/config.ts
src/system/types/cosmere.ts
src/system/util/handlebars/index.ts
src/system/util/handlebars/types.ts
src/templates/actors/character-sheet.hbs
src/templates/actors/parts/actions.hbs
src/templates/actors/parts/inventory.hbs

Partially addresses #4 
Adds the basic actions list to the character sheet and allows the user to roll/use the actions. 
TODO:

feat(character sheet): add basic actions list

---

src/style/chat/module.scss
src/system/dice/damage-roll.ts
src/templates/chat/parts/roll-details.hbs

**Type**  
This PR fixes advantage not correctly applying to damage rolls. 
Closes #84 
Rolled an attack from a character sheet, with a weapon which had the damage set to 2d10, with advantage.
**Checklist:**

fix(damage roll): make advantage correctly apply to damage rolls

---

src/style/sheets/item/module.scss
src/system/applications/item/action-sheet.ts
src/system/applications/item/talent-sheet.ts
src/system/applications/item/weapon-sheet.ts

**Type**  
This PR gives item sheets a max height. This makes it so that items with a lot of options (like weapons) don't take up the entire screen height.
Closes #92 
Opened an Item of each type and navigated to the details tab to verify the max height was applied properly (where needed).
**Checklist:**

feat(item sheets): add max height

---

src/lang/en.json
src/style/sheets/actor/module.scss
src/system/applications/actor/components/actions-list.ts
src/system/applications/actor/components/adversary/actions-list.ts
src/system/applications/actor/components/equipment-list.ts
src/system/applications/component-system/system.ts
src/system/documents/item.ts
src/templates/actors/components/actions-list.hbs
src/templates/actors/components/equipment-list.hbs

**Type**  
This PR adds the ability to add items directly from the Actor sheet, rather than having to create them from the side menu first.
Closes #87 
Tested creating actions from the Character and Adversary sheet.
**Checklist:**

feat(character sheet): add functionality to add actions directly from the sheet

---

src/lang/en.json
src/style/module.scss
src/style/sheets/actor/module.scss
src/style/sheets/item/module.scss
src/system/applications/actor/components/details.ts
src/system/applications/actor/dialogs/configure-deflect.ts
src/system/data/actor/common.ts
src/system/data/item/mixins/equippable.ts
src/templates/actors/components/details.hbs
src/templates/actors/dialogs/configure-deflect.hbs

**Type**  
This PR fixes an issue causing armor with "Always Equipped" set, to not count as equipped if it wasn't equipped at least once first. Additionally this PR implements natural deflect for Actors, which catches a lot of the edge cases where always equipped armor was needed.
Closes #106 
Created a new armor item, ensured it wasn't equipped yet, set it to always equipped and checked the deflect value of the Actor.
**Checklist:**

fix(armor): fix issue causing always equipped armor to not count as equipped and implement natural deflect on actors

---

src/system/documents/item.ts

**Type**  
This PR fixes an issue causing damage rolls that are part of an attack, not to respect their skill/attribute overrides.
Closes #101 
Created an item with different skills/attributes configured for the skill test and damage roll. Added the item to an Actor that had different values for said skills. Used the item and checked if the appropriate modifier were present.
**Checklist:**

fix(attack roll): fix issue causing damage rolls not to respect their skill/attribute config

---

src/index.ts
src/system/applications/actor/adversary-sheet.ts
src/system/applications/actor/base.ts
src/system/applications/actor/character-sheet.ts
src/system/applications/actor/components/character/goals-list.ts
src/system/applications/combat/combat-tracker.ts
src/system/applications/item/action-sheet.ts
src/system/applications/item/ancestry-sheet.ts
src/system/applications/item/armor-sheet.ts
src/system/applications/item/base.ts
src/system/applications/item/connection-sheet.ts
src/system/applications/item/culture-sheet.ts
src/system/applications/item/equipment-sheet.ts
src/system/applications/item/injury-sheet.ts
src/system/applications/item/loot-sheet.ts
src/system/applications/item/path-sheet.ts
src/system/applications/item/specialty-sheet.ts
src/system/applications/item/talent-sheet.ts
src/system/applications/item/trait-sheet.ts
src/system/applications/item/weapon-sheet.ts
src/system/constants.ts
src/system/documents/actor.ts
src/system/documents/combat.ts
src/system/documents/combatant.ts
src/system/documents/item.ts
src/system/hooks/modules/dice-so-nice.ts
src/system/hooks/sheets.ts
src/system/hooks/welcome.ts

**Type**  
A relatively minor change, but an important one. I switched all hardcoded 'cosmere-rpg' tags to refer instead to a constant that holds the system ID. If we need to change this to (for example) 'plotweaver' later for license reasons, it will save us a lot of sweat blood and tears to simply change that single constant over changing every single tag.
This also helps ensure that we don't have hard to detect mistakes such as a flag being set with a typo and polluting the object data.
System still loads, sheets still open, rolls still happen. I made sure the imports were correct so this shouldn't change any functionality at all.
**Additional …

Switch all hardcoded system tags to single constant reference

---

rollup.config.js

**Type**  
On windows, a directory must exist before writing a file to it. The release notes markdown was causing the build to fail until the build directory was created (which happens when the build finishes successfully).
I didn't bother to make an issue, but when following the instructions in CONTRIBUTING.md, I was unable to successfully build with `npm run build`
I've run the build both before and after creating a `build` directory.
N/A
_Add any other context or information here that would be useful for reviewers._

Fix build on Windows

---

src/index.ts
src/lang/en.json
src/system/applications/item/base.ts
src/system/hooks/sheets.ts
src/system/hooks/welcome.ts
src/system/settings.ts

**Type**  
Refactor the Settings script to do a couple of things:
- Create a single "getSettingValue" function that we can call without needing to import the SYSTEM ID everywhere. Also, if the foundry API for getting a setting value ever changes (which it has done in the past), we can simply change it in one place and be done.
- Create an object reference of Setting Names that can be imported elsewhere to refer to a specific setting directly without hardcoding the setting name everywhere. Also used to localise the setting key in the lang file, though unfortunately it has to be hardcoded in the lang file, so if a setting name changes we have to manually change it there.
- Setup for each loops for settings batches so the settings script isn't a huge list of duplicate code …

Centralise and Localise Settings

---

src/style/sheets/actor/character.scss

**Type**  
My first commit to the repository. Simply just fixing a minor CSS error where the font in the character sheet "Purposes and Obstacles" field is defaulting to Calibri, rather than than one of the previously used fonts
Closes #127 
Create a new "Character" actor, navigate to the goals tab, verify the font underneath the "Purpose" and "Obstacle" header.
**Screenshots (if applicable)**
Prior:
Updated:  
Let me know if I have done any of this process wrong per the contribution rules of this repository. Thanks!

Textarea not configured to inherit font-family by default

---

src/style/sheets/actor/character.scss

**Type**  
Currently, the goals and connections list are not configured to scale, and automatically force a height of 2rem for all elements. This leads to overflow issues when larger goals or connections are written. 
I have modified the height to be automatic and added a small amount of padding on the top and bottom so the text looks naturally seated within the range. The overall height for a one-line goal is the same(.25 top padding, 1.5 min-size, .25 bottom padding)
Closes #112 
Tested goals and connections of various sizes, and verify that all previous elements fit and still work as intended.
Before:
After: …

Modify goals-list and connections-list to automatically adapt to text size

---

src/declarations/foundry/client/data/documents/actor.d.ts
src/lang/en.json
src/style/chat/module.scss
src/system/dice/d20-roll.ts
src/system/documents/actor.ts
src/system/documents/chat-message.ts
src/system/documents/item.ts
src/system/utils/generic.ts
src/system/utils/templates.ts
src/templates/chat/card-tray-targets.hbs

**Type**  
Adds a collapsible list of actors that were targeted when the skill test was made. This list shows the appropriate defence values for each actor, and adds an indicator for whether or not each defence was beaten by the skill test. Target info is stored within the message flags, which means the card will persist even post reload, keeping a tray with the targets that were selected when it was made.
Closes #153.
Tested with multiple actors targeted and ensure targets are stored into the message on refresh.
**Checklist:**

Skill Test Targets Display

---

src/system/documents/item.ts

**Type**  
This PR fixes the bug causing items to no longer be marked as favorite when dropped on the favorites section
Closes #158 
2. Drop item from sheet onto favorites section
3. Item gets added to favorites list
**Checklist:**

fix(item document): fix issue causing items no longer be properly marked as favorite

---

src/style/chat/module.scss
src/system/documents/chat-message.ts
src/templates/chat/roll-damage.hbs

**Type**  
Creates a simple accordion animation on the damage total to make the swap more evident.
Completes a leftover from #138
Tested toggling between modes.
**Checklist:**

feat: animate accordion for toggling between full damage and graze

---

src/style/chat/module.scss
src/system/documents/chat-message.ts

**Type**  
Allows the repeat icon on chat cards to create a new chat message with the exact same configuration as the existing message, but with all rolls rerolled.
Closes #154 
Tested on all repeatable chat cards (i.e. chat cards that have rolls).
_Add screenshots or GIFs that help illustrate the changes, especially if they affect the UI or user-facing aspects of the system._
**Checklist:**

feat: allow chat cards to repeat

---

src/system/applications/actor/components/character/goals-list.ts
src/templates/actors/character/components/goals-list.hbs

**Type**  
This PR fixes the bug causing no new goal to get added when "add new goal" is clicked.
Closes #159 
1. Open character sheet to goals tab
2. Click "Add new goal"
3. A new goal is added to the list
**Checklist:**

fix(goals list component): fix error causing no new goal to get added when "add new goal" is clicked

---

src/packs/tables/injury-duration.json

**Type**  
_A clear and concise description of the changes you are making. What does this PR implement or fix?_
This adds double square brackets around the duration dice in two of the injury options so that the user doesn't need to manually roll the dice.
_This PR must be linked to an existing issue. Please specify the related issue number and whether this PR fully or partially resolves it. Use the format `Closes #<issue-number>` or `Partially addresses #<issue-number>`._
Partially addresses #120
_Describe how you tested the changes and how others can replicate the testing steps._
Using the same text in FVTT roll table causes the dice to …

feat(styling): add styling to injury rolls to auto-roll days

---

src/lang/en.json
src/system/applications/actor/components/actions-list.ts
src/system/applications/actor/components/equipment-list.ts

**Type**  
This PR adds a context menu option to favorite/un-favorite actions and items.
Closes #134 
2. Navigate to actions tab
3. Open context menu
4. Select "Favorite"
5. Item gets added to favorites list
6. Open context menu again
7. Select "Remove favorite"
8. Item gets removed from favorites list
**Checklist:**

feat(character sheet): add favorite context menu option for actions and items

---

src/packs/tables/injury-duration.json
src/system/documents/chat-message.ts

**Type**  
The vicious injury entry in the Injury Duration roll table had the incorrect string assigned, which led to issues when enriching injury rolls. I had a bandaid fix there in the card styling PR, but we might as well push the actual fix.
No related issue, very minor change.
Have to repack the compendium of course, but other than that all behaviour should continue working the same.
**Checklist:**

fix(compendium): fix incorrect string for vicious injury in compendium

---

src/system/applications/actor/adversary-sheet.ts
src/system/applications/actor/character-sheet.ts

**Type**  
Marks the tab body elements of both the character & adversary sheets as scrollable so their scroll state is persisted between renders.
Closes #118 
1. Open character/adversary sheet
2. Add enough items to actions to require scrolling
3. Scroll down 
4. Use the recharge context option (on an item that has limited uses)
**Checklist:**

fix(sheets): resolve issue causing the scroll state to reset after re-render

---

src/system/dice/damage-roll.ts

**Type**  
Fixes an issue discussed in #175 where damage rolls with multiple different dice types would only show the first dice type in the tooltip.
Relates to #175.
Rolled base damage and graze with different dice types, both work as expected now.
**Checklist:**

fix(chat cards): different damage dice in tooltip

---

src/lang/en.json
src/system/documents/chat-message.ts
src/templates/chat/card-injury.hbs

**Type**  
Adds a button to the injury roll chat cards that allows automatically adding the injury that was rolled to the actor that rolled it.
Closes #178
Tested with all kinds of injuries.
**Checklist:**

Add apply injury functionality

---

src/system/documents/actor.ts

**Type**  
This PR makes it so scalar attributes in the roll data correctly apply attribute bonuses.
Closes #212 
1. Create a character with unarmed. Set their STR to 4
2. Roll to see expected scale of 1d4+Athletics
3. Use effect to add bonus to STR attribute
4. Roll unarmed attack again, note scaling
**Checklist:**

fix(actor roll data): fix scalar attributes not correctly applying attribute bonuses

---

src/system/data/actor/common.ts
src/system/data/actor/index.ts
src/system/utils/handlebars/index.ts

*Type**  
**Description**
This PR makes it so the attribute bonus is correctly applied to derived statistics (e.g. movement rate)
Closes #217 
1. Add effect that modifies an attribute bonus (`system.attributes.spd.bonus` to +2)
2. Toggle effect on
3. See movement rate increase
**Checklist:**

fix(data models): fix issue causing derived statistics not to be updated when a bonus is applied

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/chore.md
.github/ISSUE_TEMPLATE/feature_request.md

**Type**  
I notice that github has issue types now so maybe we replace the pre-configures feature/bug/etc labels with these.

Update issue templates to use Types instead of Labels

---

src/lang/en.json
src/system/applications/actor/components/details.ts
src/system/applications/actor/dialogs/configure-movement-rate.ts
src/system/config.ts
src/system/data/actor/common.ts
src/system/types/config.ts
src/system/types/cosmere.ts
src/templates/actors/components/details.hbs
src/templates/actors/dialogs/configure-movement-rate.hbs

**Type**  
This PR adds support for additional movement types.
Closes #214 
1. Create actor
2. Toggle edit mode
3. Click configure movement rate
4. Edit each type to have a value
5. Hover over movement 
**Checklist:**

feat: add additional movement types

---

src/system/applications/actor/components/details.ts
src/system/applications/actor/components/resource.ts
src/system/applications/actor/dialogs/configure-defense.ts
src/system/applications/actor/dialogs/configure-deflect.ts
src/system/applications/actor/dialogs/configure-movement-rate.ts
src/system/applications/actor/dialogs/configure-recovery-die.ts
src/system/applications/actor/dialogs/configure-resource.ts
src/system/applications/actor/dialogs/configure-senses-range.ts
src/system/applications/actor/dialogs/short-rest.ts
src/system/data/actor/character.ts
src/system/data/actor/common.ts
src/system/data/fields/derived-value-field.ts
src/system/documents/actor.ts
src/system/documents/item.ts
src/system/documents/token.ts
src/system/utils/generic.ts
src/system/utils/handlebars/index.ts
src/templates/actors/components/attributes.hbs

**Type**  
This PR fixes an issue causing the health value to include the bonus twice. This PR solves the more general problem of how the derived fields are meant to be used. It simplifies use into always using the `.value` property.
Closes #225 
1. Create Active Effect set to Add 1 on `system.resources.hea.max.bonus`
2. Toggle on new effect
3. Health is increased by 1 (only)
**Checklist:**

feat(data model): improve the way derived fields are used

---

src/lang/en.json
src/style/dialog.scss
src/system/applications/dialogs/pick-dice-result.ts
src/system/dice/d20-roll.ts
src/system/dice/index.ts
src/system/dice/modifiers.ts
src/system/dice/plot-die.ts
src/templates/roll/dialogs/pick-dice-result.hbs

**Type**  
This PR adds the ability to use advantage/disadvantage with plot dice by adding a new dice term "pick" modifier (`p`). When evaluated, this modifier brings up a dialog window to pick a number of dice to keep.  
Also adds "gm pick" (`gmp`) modifier, though resolves the same as the "pick" modifier for now.
Closes #231 
1. Open an actor sheet with a weapon
2. Bring up the attack configuration dialog
3. Select "Raise the stakes" and apply advantage (or disadvantage) to the plot die
4. The dice result pick dialog comes up, pick a result
5. The chosen result is kept, the other discarded
**Checklist:**

feat(dice): implement dialog to select plot die roll result

---

src/templates/actors/adversary/parts/header.hbs

**Type**  
This PR makes the tier field on the adversary sheet editable.
Closes #230 
1. Open adversary sheet
2. Toggle edit mode
3. Edit tier
4. Refresh
5. Check tier
**Checklist:**

feat(adversary sheet): make tier editable

---

src/declarations/foundry/client/data/documents/active-effect.d.ts
src/index.ts
src/system/documents/active-effect.ts
src/system/documents/index.ts

**Type**  
This PR adds the ability to use actor roll data (`@fields`) in active effect values.
Closes #226 
1. Open character
2. Add active effect for key `system.resources.hea.max.bonus` with value `@level`
3. Toggle the effect on
4. Max health increases by the level (Note: because the level increases the base health will also go up so account for that)
**Checklist:**

feat(active effects): make actor roll data available in active effect values

---

src/system/config.ts
src/system/documents/actor.ts
src/system/types/config.ts

**Type**  
This PR adds scalar properties for powers. It exposes both the die size and effect size fields through `@scalar.power.<id>.die` & `@scalar.power.<id>.effect-size`.
Closes #215 
1. Add the Adhesion power from the playtest materials to a character
2. Use `/r 1@scalar.power.adh.die`
3. 1d4 gets rolled
4. Add Windrunner radiant path to same character
5. Adjust adhesion rank to 2
6. Use `/r 1@scalar.power.adh.die`
7. 1d6 gets rolled
**Checklist:**

feat(actor): add power scaling to roll data

---

src/system/applications/combat/combat-tracker.ts
src/system/documents/combat.ts
src/system/documents/combatant.ts
src/system/utils/handlebars/index.ts
src/templates/combat/combatant.hbs

**Type**  
For combatants that are adversaries with the boss role, this PR introduces two turns (one fast, one slow) to the combat tracker, rather than the usual one. The turn speed toggle is removed because it's unnecessary. Because both turns are tied to the same combatant, both turns are removed when the combatant is removed. Turn activation is tracked separately.
Closes #218 
1. Create an adversary actor
2. Change the adversary's role to Boss
3. Add the actor to a scene, then toggle combat state on the token
4. Behold!
5. Create additional actors of various types (characters, and adversaries of other roles) to confirm that there is no …

feat(combat): support simultaneous fast and slow turns for boss adversaries

---

src/system/data/actor/common.ts

**Type**  
This PR fixes a bug causing any defense bonus to be applied twice.
Closes #255 
2. Add effect with attribute key `system.defenses.phy.bonus` and value `1`
3. Toggle effect on
4. Physical defense goes up by 1
**Checklist:**

fix(common actor data): fix issue causing defense bonus to be included twice in defense value

---

src/system/documents/active-effect.ts

**Type**  
This PR fixes a bug causing math expressions in active effect values to result in `NaN`.
Closes #259 
2. Add active effect
3. Set attribute key to `system.resources.inv.max.bonus` and value to `1 + 1`
4. Investiture max increases by 2
**Checklist:**

fix(active effects): apply formula total to value rather than evaluated formula

---

src/lang/en.json
src/system/applications/item/base.ts
src/system/settings.ts
src/templates/item/partials/item-description-tab.hbs

**Type**  
Implements the ability to toggle whether the item sheet's main description field is expanded by default or not (defaults to false).
**Related Issue**
Closes #274.
Tested by toggling the setting and opening any item sheet.
N/A

Feat/description expansion default setting #274

---

src/system/applications/actor/base.ts
src/system/applications/item/base.ts

**Type**  
Fixes an issue where event propagation on html fields prevented the edit buttons from being clicked.
Fixes regression caused by #281.
Ensured edit buttons work on actor and item html fields.
**Checklist:**

fix: html field event propogation

---

src/style/module.scss
src/style/sheets/item/talent-tree.scss
src/style/tooltip.scss
src/system/applications/item/components/talent-tree/canvas/elements/connection.ts
src/system/applications/item/components/talent-tree/canvas/elements/index.ts
src/system/applications/item/components/talent-tree/canvas/elements/nodes/index.ts
src/system/applications/item/components/talent-tree/canvas/elements/nodes/talent-node.ts
src/system/applications/item/components/talent-tree/canvas/elements/nodes/tree-node.ts
src/system/applications/item/components/talent-tree/canvas/elements/nodes/types.ts
src/system/applications/item/components/talent-tree/canvas/elements/tree.ts
src/system/applications/item/components/talent-tree/canvas/world.ts
src/system/applications/item/components/talent-tree/talent-tree-editor.ts
src/system/applications/item/components/talent-tree/talent-tree-view.ts
src/system/types/item/talent-tree.ts

**Type**  
This PR adds support for nesting talent trees. Talent trees can be dragged on the tree as talents and will render out their contents.
Partially addresses #70 
Locally nesting talent trees
**Checklist:**

feat(talent trees): add support for nested talent trees

---

src/style/sheets/actor/module.scss
src/system/applications/actor/components/currency-list.ts
src/system/types/config.ts
src/templates/actors/components/currency-list.hbs

**Type**  
Fixes an issue where if  a currency icon is missing, there is a blank error icon. This introduces a fallback system that will show a generic icon in place of any missing icons, which is a neater solution.
Tested with the playtest materials (which have no currency icons for the registered icons) and ensured that the fallback takes effect. Tested with the handbook module to ensure icons still show up if available.
**Checklist:**

fix: currency fallback icon

---

package-lock.json
package.json
rollup.config.js
src/system/mixins/vector.d.ts
src/system/mixins/vector.ts

**Type**  
This PR fixes the bug that allows tokens to move through walls (cardinally). This bug was caused by the inclusion of the `@pixi/math-extras` library for vector math utils. These have been replaced with our own implementation.
Closes #300 
1. Place a wall in a scene
2. Place a token beside the wall
3. Move (cardinally) into the wall -> Token gets blocked by the wall
**Checklist:**

fix(vector utils): replace @pixi/math-extras dependency with own implementation

---

src/lang/en.json
src/system/types/utils.ts
src/system/utils/data.ts
src/system/utils/migration/migrations/0.2-0.3.ts
src/system/utils/migration/utils.ts

**Type**  
This PR solves the issue causing 0.2-0.3 migrations to fail if custom talent trees are present in the world. The previous implementation failed since in the type we were using a collection, however when we grab the raw data from Foundry we get back a plain object. This PR also generally makes the migration more robust by wrapping each individual document migration in its own try/catch.
Closes #302 
1. Install the test world and backups shared in test data
2. Revert to the oldest back up
3. Open the world with 0.3
4. Migration now succeeds
**Checklist:**

fix(0.2-0.3 migration): fix issue causing talent tree migrations to fail and improve migration robustness

---

src/system/applications/actor/components/character/connections-list.ts
src/system/applications/actor/components/character/goals-list.ts
src/system/applications/utils/context-menu.ts

**Type**  
The PR addresses the issue where context popups are appearing at the wrong position. The fix seems to be setting the position relative to the tab body, rather than the root element, because the `<menu/>` element's position is relative to the actual tab content.
Partially addresses #282 
Just go on a character sheet, click the triple-dot, and confirm that the popup is placed much more closely/accurately than before.
**Checklist:**

Fix incorrect context popup positioning

---

src/system/applications/actor/components/actions-list.ts

**Type**  
This PR fixes a bug causing ancestry actions to show up in the misc section instead of the ancestry actions section.
Closes #296 
1. Create new character
2. Add singer ancestry
3. Add forms of finesse
4. Check that Art form and Nimble form are both included in ancestry actions section
**Checklist:**

fix(action list component): fix issue causing ancestry actions to not be included in ancestry section

---

src/system/applications/component-system/system.ts

**Type**  
This PR fixes an issue with the way the component system assigns ids to components in nested loops (multiple levels of `#each`). The way the system got the nested index was incorrect and could cause duplicate values, causing duplicate component ids. This was only noticed/relevant for path linked skills, though could come up anywhere.
Closes #297 
2. Add Windrunner (and its surges) and Lighweaver (and its surges) to character
3. Linked skills are displayed under the correct path.
**Checklist:**

fix(component system): fix issue causing nested loop indexes to have duplicate values

---

src/system/applications/component-system/system.ts
src/system/applications/components/document-drop-list.ts
src/system/applications/components/document-reference-input.ts
src/system/applications/components/multi-value-select.ts

**Type**  
This PR fixes an issue causing our form associated components to "forget" their value when the form is submitted as result of anything but a change event from that component. 
Closes #306 
1. Create path
2. Ad linked skills
3. Update the identifier
4. Close and open item
5. Linked skills remain as they were
**Checklist:**

fix(component system): fix issue causing form associated components to lose track of their value

---

src/system/applications/actor/dialogs/configure-movement-rate.ts
src/templates/actors/dialogs/configure-movement-rate.hbs

**Type**  
Fixes an issue where movement rates weren't properly displaying in the configuration dialog. This change preserves _all_ derived members, notably including the `value` getter, so that the `derive` helper can actually make any use of the movement rates.
Closes #322 
1. Create an actor
2. Open the movement config dialog
4. Observe the actual values
5. Set mode to custom
6. Change movement rates
7. Confirm that it updates correctly in the dialog
**Screenshots (if applicable)** 
_Before:_
_After:_
**Checklist:**

fix(character sheets): properly display movement rates in config dialog

---

src/lang/en.json
src/system/applications/actor/components/actions-list.ts
src/templates/actors/components/actions-list.hbs

**Type**  
Simple issue with the "add action" tooltip not using a formatted string to insert action type.
Closes #133 
1. Open an actor sheet in edit mode
2. Go to actions tab
3. Hover over the `+` by each action category
4. Observe the tooltip updating to include category type
N/A

Fix(localization): context dependent 'add' button #133

---

src/system/data/item/power.ts
src/templates/item/power/partials/power-details-tab.hbs

**Type**  
Modifies the Power item data model and sheet template to allow for damage rolls/configuration.
Closes #333 
1. Create a new power item.
2. Go to details, change the formula/damage type
3. Roll the item from an actor
4. Confirm that a damage roll is produced
**Checklist:**

fix(items): allow power items to roll damage

---

src/system/applications/actor/dialogs/configure-resource.ts
src/templates/actors/dialogs/configure-resource.hbs

**Type**  
This PR fixes an issue with the configure resource dialog that causes the bonus value to be doubled each time the dialog is saved. Also resolves an issue causing the override (custom) input to re-apply the bonus after any change.
Closes #346 
1. Create an active effect with: key system.resources.foc.max.bonus, mode: Add, value: 2
2. Toggle effect on
3. Open the resource config dialog for focus
4. Set it to mode custom
5. Adjust the value twice
6. Click update (value should be whatever you set custom to)
7. Open the config again
8. Click update (value should not change)
**Checklist:**

fix(configure resources config): fix issue causing bonus value to double each time the dialog is saved

---

src/lang/en.json
src/system/applications/actor/components/actions-list.ts
src/system/data/item/armor.ts
src/templates/item/armor/partials/armor-details-tab.hbs

**Type**  
Makes armour items activatable so that the can contain charge tracking. This is in lieu of a later refactor to separate actions from items more distinctly, as the current approach is clunky.
Closes #338.
Tested with existing and new armor items to make sure they have the Usage section and that, when equipped, they show in the actions tab under a new armor section.
**Checklist:**

feat: armor charge tracking

---

src/index.ts

**Type**  
Adds a new vision mode "Sense" that is system appropriate (instead of "Darkvision").
Closes #320.
Tested that the new Sense mode appears on tokens and that it correctly displays vision the same way as Darkvision (for now).
**Checklist:**

feat: sense vision mode

---

src/style/sheets/item/module.scss
src/style/sheets/sheet.scss

**Type**  
Fixes an issue where items with non-square ratios would escape the bounds of their portrait square in the item list. Also fixes how items with non-square ratios show in the item sheet, now appropriately adding padding and centring the images.
Closes #334.
Tested with both types of non-square ratio images (horizontal and vertical preference) in both actor sheet item lists and in the item sheet itself.
**Checklist:**

fix: non-square ratio item portraits

---

src/system/data/actor/common.ts
src/system/dice/d20-roll.ts
src/system/documents/actor.ts

**Type**  
This change ensures that the skill displays, roll dialogs and roll calculations all correctly account for any attribute bonuses applied through Active Effects.
This is achieved mainly through the moving of where the skill mod derived data field is calculated, but also required some updates to the roll configuration dialogs to ensure correct display there too.
Closes #356
Following the reproduction steps in the linked issue (see images) and also by rolling skills from the sheet.
**Checklist:**

fix(skill mods): Ensured Attribute mods were properly accounted for

---

src/system/data/actor/common.ts

**Type**  
Fixes an issue where when no armour is equipped by an actor, all damage ignores deflect. Now, if no armour is equipped, the default deflect config is used (plus whatever effects may be active on the actor).
Tested that default deflect types are now properly deflected if no armour is equipped. If armour is equipped, the deflect types from the armour itself are used instead (even if there are fewer of them than the default configs).
**Checklist:**

fix: natural deflect types

---

src/system/applications/item/components/talent-tree/talent-tree-view.ts
src/system/utils/generic.ts

**Type**  
This PR fixes an issue where the talent tooltip on talent trees uses the short description even if it is empty. Caused by the use of the nullish coalescing operator (short description was an empty string). Also needed to add a check if the html contained actual content as a description with just whitespace was causing the same issue.
Closes #366 
1. Create talent tree item
2. Create talent item
3. Add description (not short desc)
4. Add talent to talent tree
5. Leave edit mode on talent tree
6. Hover over talent -> Ensure you see the proper description
7. Add short description to talent
8. Hover over talent -> Ensure you see the short description
9. Replace short description with several spaces (only …

fix(talent trees): fix issue causing talent hover description fallback to fail

---

LICENSE
README.md
src/declarations/foundry/client/data/documents/active-effect.d.ts
src/declarations/foundry/client/data/documents/journal-entry-page.d.ts
src/declarations/foundry/client/data/documents/journal-entry.d.ts
src/declarations/foundry/common/documents/journal-entry-page.d.ts
src/declarations/foundry/common/documents/journal-entry.d.ts
src/packs/rules/LICENSE
src/packs/rules/conditions.json
src/packs/tables/LICENSE
src/style/tooltip.scss
src/system.json
src/system/applications/actor/components/conditions.ts
src/system/config.ts
src/system/utils/uuid.ts
src/templates/actors/components/conditions.hbs

**Type**  
This PR changes the following:
- Adds a Rules compendium with Conditions journal
- Configures condition references to point to the relevant section of the page
- Adds a tooltip to the conditions component on the actor sheet with the condition effect, based on the configured reference.
Also updates the LICENSE to clarify that not all content falls under the MIT license and adds LICENSE files with separate terms where needed.
Closes #357
1. Go to compendiums -> Cosmere RPG -> Rules
2. Open the Conditions journal
3. Open an actor
4. Go to Effects & Conditions tab
5. Hover over each Condition (except dead)
**Checklist:**

feat: add rules compendium with conditions

---

src/declarations/foundry/client/data/documents/combat.d.ts
src/declarations/foundry/client/data/documents/combatant.d.ts
src/index.ts
src/system/applications/combat/combat-tracker.ts
src/system/data/combatant/combatant.ts
src/system/data/combatant/index.ts
src/system/data/index.ts
src/system/documents/combat.ts
src/system/documents/combatant.ts
src/templates/combat/combatant.hbs

**Type**  
This PR fixes the permissions errors that players receive whenever the combat state of an actor they don't control gets toggled. The combatants have been cleaned up. The combat document has been changed to handle the double boss turns directly, instead of relying on the combat tracker. 
Initially I set the the combatants up to use an actual data model instead of flags, however V12 doesn't permit users to update system fields on combatants they own. It looks like this may be fixed for V13 so leaving the data model class in even though its unused.
Closes #390 
1. Join instance as GM
2. Join instance as player in separate window
3. As GM: activate a scene with some number of actors that the player lacks …

feat(combat): refactor combat and combatants to properly handle permissions

---

src/declarations/foundry/common/abstract/data.d.ts
src/declarations/foundry/common/abstract/fields.d.ts
src/lang/en.json
src/system/api/item.ts
src/system/applications/item/dialogs/edit-event-rule.ts
src/system/constants/hooks.ts
src/system/hooks/index.ts
src/system/hooks/item-event-system/events.ts
src/system/hooks/item-event-system/index.ts
src/system/hooks/item.ts
src/system/types/config.ts
src/system/types/hooks/item.ts
src/system/types/utils.ts
src/templates/item/dialog/edit-event-rule.hbs

**Type**  
This PR adds the following:
- 2 new events that are available to item event rules: Goal completed & Goal progressed. 
- Hooks for goal progression: `progressGoal` `preProgressGoal` `updateProgressGoal` `preUpdateProgressGoal` `completeGoal` `preCompleteGoal`
- The ability to filter which event types are available to be selected for event rules on certain items — The goal completed & goal progressed events are only available for Goal items, etc. (All existing event types that were only valid for certain items have been assigned their respective filters)
Closes #382 
1. Open an Actor
2. Add a goal
3. Edit the goal
4. Add an event rule: set trigger to "Goal completed" and handler to "Grant items" and add an item …

feat(item events): add goal completed and goal progressed event types

---

src/lang/en.json
src/system/applications/item/dialogs/edit-event-rule.ts
src/system/documents/item.ts
src/system/hooks/item-event-system/handlers/index.ts
src/system/hooks/item-event-system/handlers/update-item.ts
src/system/hooks/item-event-system/handlers/use-item.ts
src/system/hooks/item-event-system/handlers/utils.ts
src/system/hooks/item-event-system/index.ts
src/system/types/config.ts
src/system/types/hooks/item.ts
src/system/types/item/event-system/event.ts
src/system/types/item/event-system/handler.ts
src/system/utils/generic.ts
src/system/utils/handlebars/index.ts
src/system/utils/templates.ts
src/templates/item/event-system/handlers/update-item.hbs
src/templates/item/event-system/handlers/use-item.hbs

**Type**  
This PR implements the "Use Item" handler, which can be used to use/roll an item when an event occurs. If used with the "Used" event it will also forward some roll options from the triggering action to the use call (fast forwarding, advantage/disadvantage, plot die).
Includes some changes to the item document to include the options in the `useItem` and `preUseItem` hooks, improved handling of temporaryModifiers, and a fix to be able to use the override formula for damage rolls as part of an attack.
Closes #381 
1. Open an actor
2. Add a one-handed weapon (weapon1) to the actor
3. Equip the weapon
4. Add a talent to the actor (preferably with no activation or utility)
5. Edit the talent and add a new event …

feat(item event system): add use item handler

---

src/system/applications/dialogs/attack-configuration.ts
src/system/applications/dialogs/roll-configuration.ts
src/templates/roll/dialogs/roll-configuration.hbs

**Type**  
As discussed on Discord, we are temporarily hiding the roll config dropdown for roll mode until the roll workflow refactor as it does not presently work and is a tricky thing to fix due to how messages are being created for attacks.
Closes #360.
Tested both types of roll config windows to ensure drop down is gone and rolls still execute, respecting the chat window roll mode.
**Checklist:**

fix: hide roll mode drop down in roll config

---

src/lang/en.json
src/system/api/actor.ts
src/system/api/general.ts
src/system/api/helper.ts
src/system/api/index.ts
src/system/api/item.ts
src/system/api/sheet.ts
src/system/api/style.ts
src/system/applications/actor/components/actions-list.ts
src/system/constants/hooks.ts
src/system/hooks/item-event-system/events.ts
src/system/hooks/item-event-system/handlers/execute-macro.ts
src/system/hooks/item-event-system/handlers/grant-expertises.ts
src/system/hooks/item-event-system/handlers/grant-items.ts
src/system/hooks/item-event-system/handlers/modify-attribute.ts
src/system/hooks/item-event-system/handlers/modify-skill-rank.ts
src/system/hooks/item-event-system/handlers/remove-expertises.ts
src/system/hooks/item-event-system/handlers/remove-items.ts
src/system/hooks/item-event-system/handlers/set-attribute.ts
src/system/hooks/item-event-system/handlers/set-skill-rank.ts
src/system/hooks/item-event-system/handlers/update-actor.ts
src/system/hooks/item-event-system/handlers/update-item.ts
src/system/hooks/item-event-system/handlers/use-item.ts
src/system/types/config.ts
src/system/types/hooks/api.ts
src/system/types/hooks/module.ts

**Type**  
This PR overhauls the config registration API so that it no longer breaks the whole stack when an error is encountered. Instead, it creates a stack of error logs that will eventually be displayed into a pop-up dialog that notifies the user. Individual failures now are gracefully handled and the registration process continues (unless a strict flag is passed).
Improvements are also made to what is considered a failure and what isn't. If a config registration is identical to one already existing, it is simply marked as successful and ignored (for use by the multiple premium modules registering the same things, for example). Also, this PR introduces a system of priority values for …

refactor: config register api changes

---

src/templates/actors/character/components/goals-list.hbs

**Type**  
The goal context menu was not functioning, as the edit and remove options didn't do anything. This PR restores the old action names.
1. Create a character.
2. Make sure they have at least one goal
3. Try to edit from the context menu
4. Try to remove from the context menu
**Checklist:**

fix(characters): restore goal edit/remove functionality

---

src/lang/en.json
src/system/config.ts
src/system/types/cosmere.ts

**Type**  
Very simple addition to the config, registers an 'adversary action' subtype of action, alongside Ancestry Action and Basic Action.
Closes #409 
Create an action, go to details tab, ensure that Adversary Action appears in the list.
N/A

Feat: Register Adversary Actions Action Type

---

src/declarations/foundry/client/data/abstract/client-document.d.ts
src/index.ts
src/style/sheets/journal.scss
src/style/sheets/module.scss
src/system/documents/item.ts
src/system/ui/editor.ts
src/system/utils/embed/index.ts
src/system/utils/embed/item/generic.ts
src/system/utils/embed/item/index.ts
src/system/utils/embed/item/talent.ts
src/system/utils/embed/types.ts
src/system/utils/handlebars/index.ts
src/system/utils/templates.ts
src/templates/item/talent/embed.hbs

**Type**  
Adds `@Embed` support for talents and provides general scaffolding for `@Embed` support for other documents.
Partially addresses #422 
2. Create page
3. Edit page
4. Drag talent onto page
5. Change `@UUID` into `@Embed`, remove the label, and set inline
6. Save page
7. Ensure talent renders
8. Click link in header and ensure item opens
9. Drag talent from journal directly onto sheet (grab anywhere)
10. Edit page
11. Add `tree=<uuid>` within the square brackets, where `uuid` is that of a talent tree that contains the talent. 
12. Save page
13. Ensure talent renders and prerequisites are included
**Checklist:**

feat(item embed): add talent embed support

---

src/system/utils/embed/item/action.ts
src/system/utils/embed/item/generic.ts
src/system/utils/embed/item/index.ts
src/system/utils/templates.ts
src/templates/item/action/embed.hbs

**Type**  
Add `@Embed` support for actions.
Partially addresses #422 
2. Create page
3. Edit page
4. Drag action onto page
5. Replace `@UUID` with `@Embed`, set inline, and remove label
6. Save page
7. Ensure action is rendered
8. Click link in top right and ensure it links to the item
9. Drag action from journal directly onto sheet (grab anywhere)
**Checklist:**

feat(item embed): add action embed support

---

src/style/sheets/journal.scss
src/system/hooks/index.ts
src/system/hooks/journal.ts
src/system/utils/enrichers.ts

**Type**  
This PR adds a content link enricher (`@Link`) that can be used to add draggable content linking to any arbitrary journal content. This is useful for when you want embedding-link behavior but the desired journal content doesn't match the `@Embed` output (for example when the Item's description text differs from what you want to have included in the journal).
Partially addresses #422 
2. Create page
3. Edit page
4. Add some journal content, the first line should be a header
5. Drag an item onto the page, before the content
6. Change `@UUID` to `@Link`, remove label
7. Below content add `@Link`, no brackets (serves as closing tag)
8. Save page
9. Ensure header now has link icon
10. Click link …

feat(enrichers): add content link enricher

---

src/style/sheets/journal.scss
src/system/applications/canvas/viewport.ts
src/system/applications/item/base.ts
src/system/applications/item/components/talent-tree/talent-tree-view.ts
src/system/applications/item/embeds/talent-tree-embed.ts
src/system/applications/item/mixins/talents-tab.ts
src/system/applications/mixins/tabs.ts
src/system/documents/item.ts
src/system/utils/embed/item/index.ts
src/system/utils/embed/item/talent-tree.ts
src/system/utils/templates.ts
src/templates/item/talent-tree/embed.hbs

**Type**  
Adds `@Embed` support for talent trees.
Partially addresses #422 
2. Create page
3. Edit page
4. Drag talent tree item onto page
5. Replace `@UUID` with `@Embed`, remove label and set inline
6. Save page
7. Ensure talent tree renders
8. Click link in top right corner, and ensure talent tree item opens
9. Edit page
10. Include `link=<uuid>` where `uuid` is the uuid of a Path Item 
11. Save page
12. Click link in top right corner, ensure the linked item's talent tab now opens
13. Edit page
14. Include `x=150 y=150 zoom=.6` (may have to set these to different values for your talent tree)
15. Save page
16. Ensure the talent tree embed is now offset to the specified location and changed to the …

feat(item embed): add talent tree embed support

---

src/system/utils/embed/item/culture.ts
src/system/utils/embed/item/generic.ts
src/system/utils/embed/item/index.ts
src/system/utils/templates.ts
src/templates/item/culture/embed.hbs

**Type**  
Adds `@Embed` support for cultures
Partially addresses #422
2. Create page
3. Edit page
4. Drag culture onto the page
5. Change `@UUID` into `@Embed`, remove the label, and set inline
6. Save page
7. Ensure culture renders
8. Click link in the header and ensure item opens
9. Drag culture from journal directly onto sheet (grab anywhere)
**Screenshots (if applicable)**
**Checklist:**

feat(item embed): add culture embed support

---

src/system/utils/embed/item/ancestry.ts
src/system/utils/embed/item/generic.ts
src/system/utils/embed/item/index.ts
src/system/utils/templates.ts
src/templates/item/ancestry/embed.hbs

**Type**  
Adds `@Embed` support for ancestries. Ancestries embeds also have the ability to pass the `talents` flag (`@Embed[<uuid> talents]`), which instead embeds the associated talent tree.
Partially Addresses #422 
2. Create page
3. Edit page
4. Drag an ancestry, with an associated talent tree, onto the page
5. Replace `@UUID` with `@Embed`, set inline, and remove label
6. Save page
7. Ensure ancestry renders 
8. Click the link icon in the top right of the header, ensure the item opens
9. Close the item
10. Drag the ancestry directly onto a character sheet, ensure it gets added (grab anywhere)
11. Edit the page
12. add the `talents` flag to the embed (`@Embed[<uuid> inline talents]`)
13. Save the …

feat(item-embeds): add ancestry embed support

---

src/system/api/item.ts

**Type**  
This PR changes the default host for events from `owner` to `user`, which was causing certain events to only fire for the original GM user.
Closes #447 
1. Connect with original GM user
2. Connect with second user
3. Add an event rule to any non-weapon activatable item (action, talent, etc.)
4. Set trigger to "Used"
5. Set handler type to "Use item"
6. Set target to "Equipped Weapon"
7. Set damage Bonus to "2d4"
8. Click update
9. Ensure a weapon is equipped
10. Use the item from the second user
**Checklist:**

fix(event system): change default event host to source

---

src/style/sheets/item/module.scss
src/system/data/actor/common.ts
src/system/utils/handlebars/index.ts

**Type**  
Fixes an issue where multiplying decimals for currency totals and item weight totals would occasionally result in very long floating points that break the UI.
Closes #437 
Tested for both currency total fields and for item weight totals to ensure that items with value or weight of 0.x do not cause more than 2 decimal points to ever appear in the UI.
**Checklist:**

fix: currency and weight rounding errors 437

---

src/system/applications/actor/base.ts

**Type**  
Fixes an issue where rapidly toggling the edit mode slider would completely break the sheet due to an attempt by the renderer to minimise and toggle on/off edit at the same time. This was being caused by a race condition between listeners, and event.stopPropogation on the edit toggle did nothing because the header listener listens for a different click event (dbl click). Since the dbl click to minimise is default behaviour, the only way to block it is to add our own dblclick listener on the edit slider that stops propogation if the slider is double clicked.
Closes #417 
Tested by rapidly clicking the edit moddle toggle with a mouse …

fix: sheet edit mode toggle breaking bug

---

src/lang/en.json
src/style.scss
src/style/sheets/actor/module.scss
src/system/applications/actor/components/attributes.ts
src/templates/actors/components/attributes.hbs

**Type**  
This PR changes the attributes component to set the attribute input value to the source value (unmodified by effects) when focussed. Also adds an indicator that the attribute is being modified by an effect. Also consolidates raw and bonus value so they are both properly reflected in edit mode (bonus no longer only visible in view mode)
Closes #429 
1. Create a character
2. Add an item
3. Add an effect to that item, set attribute key to `system.attributes.str.value`, mode to `add`, and effect value to `2`
4. Ensure strength is now 2
5. Click on the strength attribute input to edit it
6. Ensure value changes to 0
7. Edit value to 2
8. Unfocus input
9. Ensure value changes to 4
10. Change effect attribute key to …

feat(attributes component): update input to use source value when editing and add effect indicator

---

src/system/documents/chat-message.ts

**Type**  
Fixes an issue where UUID links and inline rolls in chat card descriptions would not work, as their click event would be picked up instead by the collapsible behaviour and block further propagation. Links and inline rolls should now appropriately be detected by the collapsible listener and behave correctly.
Closes #442.
Tested with UUID links, journal references, and inline rolls within chat cards to make sure all 3 work appropriately. Also ensured collapsible behaviour still works if clicking anywhere in the description that isn't one of those links. Checked enrichers for regression.
_Add screenshots …

fix: chat card links

---

src/system/hooks/compendium.ts
src/system/hooks/index.ts

**Type**  
Adds a hook to set the default sorting mode (picked up from flags) on compendiums. Sorting mode is only set if no sorting mode is configured in the settings for the given compendium (i.e. only the first time).
Closes #440
1. Add default sorting mode flag to a compendium in its module.json (the compendium must be sorted)
```json
"flags": {
"cosmere-rpg": {
"defaultSortingMode": "m"
}
}
```
2. Open the compendium 
**Checklist:**

feat(hooks): add hook to set default sorting mode for compendiums

---

src/lang/en.json
src/system/hooks/item-event-system/handlers/grant-expertises.ts
src/system/hooks/item-event-system/handlers/grant-items.ts
src/system/hooks/item-event-system/handlers/modify-attribute.ts
src/system/hooks/item-event-system/handlers/modify-skill-rank.ts
src/system/hooks/item-event-system/handlers/remove-expertises.ts
src/system/hooks/item-event-system/handlers/remove-items.ts
src/system/hooks/item-event-system/handlers/set-attribute.ts
src/system/hooks/item-event-system/handlers/set-skill-rank.ts
src/system/hooks/item-event-system/handlers/update-actor.ts
src/system/hooks/item-event-system/handlers/update-item.ts
src/system/hooks/item-event-system/handlers/use-item.ts
src/system/hooks/item-event-system/index.ts
src/system/types/config.ts
src/system/types/item/event-system/event.ts

**Type**  
Fixes the issue of the event system loop detection triggering when importing large quantities of items by improving the detection mechanism. Before the system was simply checking if a certain number (50) of events was fired in quick succession (within 200ms of each other). The new system tracks event chain depth and triggers whenever any individual chain of events exceeds 10, or whenever an extremely large amount of events (1000) of the same type gets fired in quick succession. This last check is still necessary as we can't track event chain depth through the `execute-macro` handler (or potentially custom handlers).
Closes #403 
1. Create actor
2. Create item
3. Add event to item
4. Set trigger to "Added to …

fix(item event system): improve event loop detection

---

src/system/utils/migration/migrations/0.3-1.0.ts

**Type**  
Fixes an issue where the migration of grant rules would fail because the stored data was an object in same cases and an array in others. 
—
Ran migration against an older compendium
**Checklist:**

fix(0.3-1.0 migration): fix issue where some grant rules would fail to migrate

---

src/system/data/item/goal.ts
src/system/documents/item.ts

**Type**  
Some attempts to import the 'Goal' item from the item types directory were left after the recent migration of goal rewards to the events system
Build warning is gone.
N/A

Chore: Clear Unused Goal Item Type Imports

---

src/system/api/general.ts
src/system/api/sheet.ts
src/system/api/utils.ts

**Type**  
Fixes the issue causing the api to display an error when multiple modules register the same currencies/inventory sections. 
Closes #489 
1. Load up a world with multiple modules that register the same currencies and/or inventory sections
**Checklist:**

fix(api): fix issue causing duplicate registrations to not get detected properly

---

src/system/applications/actor/components/adversary/skills.ts
src/system/applications/actor/components/immunities.ts
src/system/applications/components/expertises-list.ts
src/templates/actors/adversary/components/skills.hbs

**Type**  
Fixes an issue where skills, expertises, and immunities section would attempt to update an actor flag on destroy, which would throw errors when doing so for locked actors.
Closes #490.
Tested locked actors to see that no errors are thrown on close. Tested also that non-locked actors still have full functionality as normal.
_Add screenshots or GIFs that help illustrate the changes, especially if they affect the UI or user-facing aspects of the system._
**Checklist:**

fix: errors on closing locked actors

---

src/style/dialog.scss
src/style/sheets/actor/adversary.scss

**Type**  
This just adds styling to two main areas where select options dropdowns didn't have it previously; adversary role+size selector and talent prereq dialog.
Closes #522 and #526 
1. Create and open adversary sheet
2. observe styling in details header section of sheet
3. click on the 'minion' roles dropdown
4. see new styling
5. click on the 'medium' sizes dropdown
6. see new styling
7. create and open a talent tree item
8. add any talent to it
9. add a prerequisite to the talent
10. click the dropdown to select a prerequisite type, attribute, or skill target
11. see new styling
**Checklist:** …

Fix(styling): Add Styling to Several Select Options Menus

---

src/lang/en.json
src/style/chat/module.scss
src/system/applications/actor/components/actions-list.ts
src/templates/actors/character/components/paths.hbs
src/templates/actors/components/attributes.hbs
src/templates/chat/roll-damage.hbs
src/templates/item/components/event-rules-list.hbs

**Type**  
Updates the localization in several areas to reduce the number of hardcoded strings:
1. "DEF" label in actor attributes is now tied to a new key: `COSMERE.Actor.Sheet.Attributes.Defense`
2. "Path" label in actor's paths list is now tied to the existing key `COSMERE.Item.Type.Path.label`
3. "Graze" label in chat message damage formula is now properly localized, and the relevant styling is more generic
4. The "Add Basic Action" button tooltip is now tied to the existing key `COSMERE.Item.Action.Type.Basic.Label`, as its default label already mentions that it's an action.
Partially addresses #518 
Closes #542 
Confirm that all of the …

chore(localization): general localization update to reduce hardcoding

---

src/system/api/actor.ts
src/system/config.ts
src/system/documents/actor.ts
src/system/types/config.ts

**Type**  
This adds the ability to dynamically register 'roll data' in the config via the API, which is then resolved in the getRollData() function for the actor sheets. It allows an arbitrary amount of data, can include nested keys, acquire data from the actor using nested keys, and specify the subtype of actor it should be applied to. It also supports mathematical operators in the list, defaulting to addition and keeping the last operator set for future operations.
Resolves #548 
I registered the following values via a module and checked they appeared in the actor roll data and resolved appropriately:
```js
export const ROLL_DATA: …
```

Feat: Add Roll Data Registration to API

---

src/system/documents/actor.ts

**Type**  
This simplifies the way that the roll data config handles overrides, existing keys, etc. It also reduces the likelihood of erroneously and aggressively overriding existing roll data for no reason. Finally, it adds a simple deepMerge util for combining existing roll-data and module-defined roll-data more thoroughly.
Fixes #551 
Define some roll data in a module, using various options and formula. Check actor.getRollData() in console from foundry app.
N/A
N/A

Fix: Adjust Roll Data Override to be Less Aggressive

---

src/style/sheets/journal.scss
src/system/utils/embed/item/generic.ts
src/templates/item/action/embed.hbs
src/templates/item/generic/embed.hbs

**Type**  
This PR adds the ability to configure the heading for item embeds.
Closes #555 
1. Create journal and add page
2. Drag item (e.g. action) onto page
3. Replace `@UUID` with `@Embed`, set `inline`
4. Save the page
5. Ensure embed shows WITH heading
6. Edit the page, update embed: set `heading=false`
7. Save the page
8. Ensure embed shows no heading and has the label (item name) prepended to the description
9. Edit the page, update embed: set `prependLabel=false`
10. Save the page
11. Ensure embed shows only the description
**Checklist:**

feat(item embeds): make heading configurable
