- src/system/applications/actor/base-sheet.ts
- src/templates/actors/character-sheet.hbs
- src/templates/actors/parts/inventory.hbs
> feat(character sheet): add inventory list

- src/system/data/actor/character.ts
> feat(character data): add purpose, obstacle, goals, and connections

- src/declarations/foundry/client/data/documents/active-effect.d.ts
- src/declarations/foundry/client/data/documents/item.d.ts
- src/index.ts
- src/lang/en.json
- src/style/sheets/item/module.scss
- src/style/sheets/module.scss
- src/style/sheets/sheet.scss
- src/system/applications/actor/components/effects-list.ts
- src/system/applications/index.ts
- src/system/applications/item/base.ts
- src/system/applications/item/components/effects-list.ts
- src/system/applications/item/components/header.ts
- src/system/applications/item/components/index.ts
- src/system/applications/item/culture-sheet.ts
- src/system/applications/item/index.ts
- src/system/applications/mixins/editor.ts
- src/system/documents/item.ts
- src/system/util/handlebars/index.ts
- src/templates/actors/components/effects-list.hbs
- src/templates/item/components/effects-list.hbs
- src/templates/item/components/header.hbs
- src/templates/item/culture/parts/sheet-content.hbs
- src/templates/item/partials/item-description-tab.hbs
- src/templates/item/partials/item-effects-tab.hbs
> feat(sheets): add culture item sheet

- package.json
- src/declarations/foundry/common/abstract/data.d.ts
- src/declarations/foundry/common/abstract/fields.d.ts
- src/index.ts
- src/lang/en.json
- src/style/sheets/item/module.scss
- src/system/applications/item/base.ts
- src/system/applications/item/components/details-id.ts
- src/system/applications/item/components/details-type.ts
- src/system/applications/item/components/index.ts
- src/system/applications/item/index.ts
- src/system/applications/item/path-sheet.ts
- src/system/data/item/mixins/id.ts
- src/system/data/item/mixins/typed.ts
- src/system/data/item/path.ts
- src/system/documents/item.ts
- src/system/util/handlebars/index.ts
- src/templates/general/tabs.hbs
- src/templates/item/components/details-id.hbs
- src/templates/item/components/details-type.hbs
- src/templates/item/partials/item-details-tab.hbs
- src/templates/item/path/parts/sheet-content.hbs
> feat: implement path item sheet

- src/declarations/foundry/client/data/documents/item.d.ts
- src/index.ts
- src/lang/en.json
- src/system/applications/actor/components/details.ts
- src/system/applications/item/components/header.ts
- src/system/applications/item/connection-sheet.ts
- src/system/applications/item/index.ts
- src/system/documents/item.ts
- src/templates/item/connection/parts/sheet-content.hbs
> feat(item sheets): implement connection item sheet

- src/index.ts
- src/lang/en.json
- src/style/sheets/item/module.scss
- src/system/applications/item/index.ts
- src/system/applications/item/injury-sheet.ts
- src/system/data/item/injury.ts
- src/system/data/item/mixins/typed.ts
- src/system/data/item/path.ts
- src/system/documents/item.ts
- src/system/util/handlebars/index.ts
- src/templates/item/injury/partials/injury-details-tab.hbs
- src/templates/item/injury/parts/sheet-content.hbs
> feat(item sheets): implement injury item sheet

- src/index.ts
- src/lang/en.json
- src/style/sheets/item/module.scss
- src/system/applications/components/id-input.ts
- src/system/applications/components/index.ts
- src/system/applications/item/components/details-id.ts
- src/system/applications/item/index.ts
- src/system/applications/item/specialty-sheet.ts
- src/system/data/item/mixins/id.ts
- src/system/documents/item.ts
- src/system/util/handlebars/index.ts
- src/templates/general/components/id-input.hbs
- src/templates/item/components/details-id.hbs
- src/templates/item/specialty/partials/specialty-details-tab.hbs
- src/templates/item/specialty/parts/sheet-content.hbs
> feat(item-sheets): implement specialty item sheet

- src/index.ts
- src/lang/en.json
- src/style/sheets/item/module.scss
- src/system/api.ts
- src/system/applications/item/base.ts
- src/system/applications/item/components/index.ts
- src/system/applications/item/components/properties.ts
- src/system/applications/item/index.ts
- src/system/applications/item/loot-sheet.ts
- src/system/config.ts
- src/system/data/item/loot.ts
- src/system/data/item/mixins/physical.ts
- src/system/documents/item.ts
- src/system/types/config.ts
- src/system/util/handlebars/index.ts
- src/templates/item/components/properties.hbs
- src/templates/item/loot/partials/loot-details-tab.hbs
- src/templates/item/loot/parts/sheet-content.hbs
- src/templates/item/partials/item-description-tab.hbs
> feat(item sheets): implement loot item sheet

- src/index.ts
- src/lang/en.json
- src/style/sheets/item/module.scss
- src/system/applications/item/armor-sheet.ts
- src/system/applications/item/components/details-equip.ts
- src/system/applications/item/components/index.ts
- src/system/applications/item/index.ts
- src/system/data/item/armor.ts
- src/system/data/item/mixins/equippable.ts
- src/system/data/item/mixins/traits.ts
- src/system/data/item/weapon.ts
- src/system/documents/item.ts
- src/system/util/handlebars/index.ts
- src/templates/item/armor/partials/armor-details-tab.hbs
- src/templates/item/armor/parts/sheet-content.hbs
- src/templates/item/components/details-equip.hbs
> feat(item sheets): implement armor item sheet

- src/index.ts
- src/lang/en.json
- src/style/sheets/item/module.scss
- src/system/applications/item/base.ts
- src/system/applications/item/components/details-activation.ts
- src/system/applications/item/components/index.ts
- src/system/applications/item/index.ts
- src/system/applications/item/trait-sheet.ts
- src/system/config.ts
- src/system/data/item/mixins/activatable.ts
- src/system/documents/item.ts
- src/system/types/cosmere.ts
- src/templates/item/components/details-activation.hbs
- src/templates/item/partials/item-details-tab.hbs
- src/templates/item/trait/parts/sheet-content.hbs
> feat(item sheets): implement trait item sheet

- src/index.ts
- src/lang/en.json
- src/style/sheets/actor/module.scss
- src/style/sheets/item/module.scss
- src/system/applications/actor/components/actions-list.ts
- src/system/applications/item/action-sheet.ts
- src/system/applications/item/base.ts
- src/system/applications/item/components/details-activation.ts
- src/system/applications/item/components/details-damage.ts
- src/system/applications/item/components/index.ts
- src/system/applications/item/index.ts
- src/system/config.ts
- src/system/data/item/action.ts
- src/system/data/item/mixins/activatable.ts
- src/system/data/item/mixins/typed.ts
- src/system/documents/item.ts
- src/system/types/config.ts
- src/system/types/cosmere.ts
- src/system/util/handlebars/index.ts
- src/system/util/handlebars/types.ts
- src/templates/actors/components/actions-list.hbs
- src/templates/item/action/parts/sheet-content.hbs
- src/templates/item/components/details-activation.hbs
- src/templates/item/components/details-damage.hbs
- src/templates/item/components/details-type.hbs
- src/templates/item/partials/item-details-tab.hbs
> feat(item sheets): implement action item sheets

- src/index.ts
- src/lang/en.json
- src/style.scss
- src/style/dialog.scss
- src/style/sheets/item/module.scss
- src/style/sheets/sheet.scss
- src/system/applications/component-system/mixin.ts
- src/system/applications/component-system/system.ts
- src/system/applications/components/id-input.ts
- src/system/applications/item/components/details-activation.ts
- src/system/applications/item/components/index.ts
- src/system/applications/item/components/talent-prerequisites.ts
- src/system/applications/item/dialogs/edit-talent-prerequisite.ts
- src/system/applications/item/index.ts
- src/system/applications/item/talent-sheet.ts
- src/system/config.ts
- src/system/data/item/mixins/activatable.ts
- src/system/data/item/talent.ts
- src/system/documents/actor.ts
- src/system/documents/item.ts
- src/system/types/config.ts
- src/system/types/cosmere.ts
- src/system/util/handlebars/index.ts
- src/templates/general/components/id-input.hbs
- src/templates/item/components/details-activation.hbs
- src/templates/item/talent/components/prerequisites.hbs
- src/templates/item/talent/dialogs/edit-prerequisite.hbs
- src/templates/item/talent/partials/talent-details-tab.hbs
- src/templates/item/talent/parts/sheet-content.hbs
> feat(item sheets): implement talent item sheet

- src/index.ts
- src/lang/en.json
- src/style/sheets/item/module.scss
- src/system/applications/item/base.ts
- src/system/applications/item/components/details-attack.ts
- src/system/applications/item/components/details-damage.ts
- src/system/applications/item/components/details-equip.ts
- src/system/applications/item/components/index.ts
- src/system/applications/item/index.ts
- src/system/applications/item/weapon-sheet.ts
- src/system/config.ts
- src/system/data/item/mixins/attacking.ts
- src/system/data/item/weapon.ts
- src/system/documents/item.ts
- src/system/types/config.ts
- src/system/util/handlebars/index.ts
- src/templates/item/armor/partials/armor-details-tab.hbs
- src/templates/item/components/details-attack.hbs
- src/templates/item/components/details-equip.hbs
- src/templates/item/partials/item-details-tab.hbs
> feat(item sheets): implement weapon item sheet

- package-lock.json
- package.json
- scripts/pack.js
- src/declarations/foundry/client/data/documents/table-result.d.ts
- src/lang/en.json
- src/packs/tables/injury-duration.json
- src/system.json
- src/system/applications/actor/components/injuries-list.ts
- src/system/applications/actor/components/resource.ts
- src/system/config.ts
- src/system/data/actor/common.ts
- src/system/data/item/injury.ts
- src/system/documents/actor.ts
- src/system/documents/chat-message.ts
- src/system/types/config.ts
- src/templates/actors/components/injuries-list.hbs
- src/templates/actors/components/resource.hbs
> feat: implement injury rolls

- src/system/applications/actor/components/character/culture.ts
- src/system/documents/actor.ts
- src/templates/actors/character/partials/char-details-tab.hbs
**Type**  
This PR makes it possible to add multiple cultures to a character
Closes #81 
Tested in foundry by first removing all cultures, before adding multiple new ones.
**Checklist:**
> fix(character): make it possible to add multiple cultures to a character

- README.md
**Type**  
Markdown updated to include installation instructions for the Bridge Nine mappack
Closes #145 
Open GitHub and check how the updated markdown looks.
Since this got discussed during the test stream figured I would just finish it off
> Update markdown to include Bridge Nine playtest.

- src/system/hooks/index.ts
- src/system/hooks/theme.ts
**Type**  
Temporary fix for the light theme issue with sheets.
Partially addresses #80 
Set color scheme to light and checked the character sheet.
**Checklist:**
> chore: add hooks to forcefully set dark theme regardless of user configuration

- README.md
**Type**  
Noticed the username was still the old owner username
N.A.
N.A.
N.A.
**Additional context**
> docs(readme): update github username in URL to manifest URLs

- src/lang/en.json
- src/style/sheets/item/module.scss
- src/system/applications/item/base.ts
- src/system/documents/item.ts
- src/templates/item/partials/item-description-tab.hbs
**Type**  
PR implements the ability to view/edit the short and chat descriptions from the description tab of an item. If an item has these then will show in chat instead of full description with a priority of chat>short>full.
Closes #141 
So far have tested giving items combinations of chat/short/full descriptions to confirm correct version appears in chat. Have also tested new collapsibles work and am in the process of figuring out how to improve the prose-mirror editing.
Item on opening:
Expanded short and chat descriptions:
Item on clicking short description edit button:
Description in chat when chat …
> Feat: Short Item Descriptions for Chat

- src/system/applications/actor/base.ts
- src/system/applications/actor/components/equipment-list.ts
- src/system/data/actor/common.ts
**Type**  
Fixes an issue where changing item quantities would not correctly update the currency list with the correct values.
Fix for an issue caused by #43.
Tested by changing currency both within the item sheet and within the actor sheet.
**Checklist:**
> fix: correctly evaluate currency quantity

- src/system/applications/actor/base.ts
- src/system/applications/item/base.ts
**Type**  
Fixes an issue where event listeners added to the HTML fields were also triggering on items in the item lists, causing odd behaviour with collapsibles.
Fixes an issue introduced by #246.
Tested that behaviour has returned to normal for item lists.
_Add screenshots or GIFs that help illustrate the changes, especially if they affect the UI or user-facing aspects of the system._
**Checklist:**
> fix: collapsible field behaviours

- src/system/utils/talent-tree.ts
**Type**  
Fixes the broken prerequisites checks.
Checked on path linked talent tree
**Checklist:**
> fix(talent tree): fix talents and level prereq checks

- src/system/documents/item.ts
**Type**  
Fixes the issue causing the consume dialog to always appear.
Closes #372 
1. Add axe to character
2. Equip axe
3. Use axe
**Checklist:**
> fix(item usage): fix issue causing the consume dialog to appear when using items that do not have resource consumption configured

- src/lang/en.json
**Type**  
Updates the localisation for Traits to Features
Closes #364 
1. Navigate to Items tab in side menu
2. Click "Create Item" -> Choose "Adversary Feature"
3. Ensure type in the top right, reads "Feature"
4. Collapse the sheet and ensure the type reads "Adversary Feature"
5. Open an adversary sheet -> ensure the section reads "Features"
**Checklist:**
> feat(lang): update localization from traits to features

- src/lang/en.json
- src/system/applications/components/multi-value-select.ts
- src/system/applications/dialogs/edit-expertises.ts
- src/system/hooks/item-event-system/handlers/grant-expertises.ts
- src/templates/general/dialogs/edit-expertises.hbs
- src/templates/item/event-system/handlers/grant-expertises.hbs
**Type**  
Adds the option to replace granted expertises if the actor already posses them to the "Grant expertises" handler. Also provides a configuration option to limit the expertise categories available during replacement.
Also adds the ability to let the user pick a number of expertises, instead of granting specific ones.
—
1. Create item
2. Add event
3. Set trigger to "Added to Actor"
4. Set handler to "Grant expertises"
5. Pick an expertise to set
6. Tick "Allow Replacement"
7. Select a number of categories for replacement 
8. Click update
9. Drag the item onto a character
10. Ensure the expertise was granted as normal
11. Drag the item onto the same character again
12. Ensure a dialog is opened where you can …
> feat(events system): add replacement option for grant-expertises handler

- src/lang/en.json
**Type**  
Updates the welcome message to be appropriate for release.
Closes #488 
1. Create and load into a new world
**Checklist:**
> chore: update welcome message for release
